# Enables or disables portals during the game.
portalsEnabled: false

# The time in seconds between each swap
swapTime: 60

# The time in seconds for the grace period
gracePeriod: 60

# The chance during a swap the teleportation will be canceled
cancelSwapChance: 0

# The time the game should start warning players a swap will take place soon.
swapWarningTime: 10
