name: ${project.name}
authors: [James Gavin]
version: ${project.version}-${git.commit.id.abbrev}
main: ${project.groupId}.${project.artifactId}
api-version: 1.16
website: jmsgvn.com
description: ${timestamp}